name: agua_coach_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.3.2
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  build_runner: ^2.1.7
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  bloc_test: ^9.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
